name: Deploy React
on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tlaurent1985/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true react-test npm test
      - run: docker build -t tlaurent1985/multi-client ./client
      - run: docker build -t tlaurent1985/multi-nginx ./nginx
      - run: docker build -t tlaurent1985/multi-server ./server
      - run: docker build -t tlaurent1985/multi-worker ./worker
